apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestas-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encuestas-back
  template:
    metadata:
      labels:
        app: encuestas-back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: encuestas-back
        image: survey4.azurecr.io/encuestas-back:v1
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: encuestas-back
spec:
  selector:
    app: encuestas-back
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

