---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encuestas-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: encuestas-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: encuestas-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: encuestas-front
          image: survey4.azurecr.io/encuestas-front:v1
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: encuestas-front
spec:
  selector:
    app: encuestas-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
